src/Entity/Games.php
<?php

namespace App\Entity;

use App\Repository\GamesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Entity\Users;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=GamesRepository::class)
 * @Vich\Uploadable
 */
class Games
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;


    /**
     * @Vich\UploadableField(mapping="images_games", fileNameProperty="Image")
     * @var File
     */
    public $ImageFile;


    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="game")
     */
    private $notes;

    /**
     * @ORM\ManyToMany(targetEntity=Users::class, inversedBy="games")
     */
    private $users;

    /**
     * @ORM\ManyToMany(targetEntity=Genres::class, inversedBy="games")
     */
    private $genres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     */
    private $favorite;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    /**
     *@param string|null $Image
     *@return $this 
     */
    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function setImageFile(?File $Image): self
    {
        $this->ImageFile = $Image;
        if($Image) $this->updatedAt = new \DateTime();
        return $this;
    }

    public function getDate()
    {
        return $this->Date;
    }

    public function setDate($Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    /**
     * @return Collection|Notes[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Notes $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setGame($this);
        }

        return $this;
    }

    public function removeNote(Notes $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getGame() === $this) {
                $note->setGame(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Users[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Users $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
        }

        return $this;
    }

    public function removeUser(Users $user): self
    {
        $this->users->removeElement($user);

        return $this;
    }

    /**
     * @return Collection|Genres[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genres $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genres $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getFavorite(): ?bool
    {
        return $this->favorite;
    }

    public function setFavorite(bool $favorite): self
    {
        $this->favorite = $favorite;

        return $this;
    }
}

src/Entity/Notes.php
<?php

namespace App\Entity;

use App\Repository\NotesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NotesRepository::class)
 */
class Notes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Etat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="notes")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Games::class, inversedBy="notes")
     */
    private $game;

    /**
     * @ORM\Column(type="integer")
     */
    private $note;
  

    public function __construct()
    {
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->Etat;
    }

    public function setEtat(bool $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function __toString()
    {
        return $this->description;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getGame(): ?Games
    {
        return $this->game;
    }

    public function setGame(?Games $game): self
    {
        $this->game = $game;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;



/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pseudonyme;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="user")
     */
    private $notes;

    /**
     * @ORM\ManyToMany(targetEntity=Games::class, mappedBy="users")
     */
    private $games;
    
    public function __construct()
    {
        $this->notes = new ArrayCollection();
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    public function getPseudonyme(): ?string
    {
        return $this->Pseudonyme;
    }

    public function setPseudonyme(string $Pseudonyme): self
    {
        $this->Pseudonyme = $Pseudonyme;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Notes[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Notes $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setUser($this);
        }

        return $this;
    }

    public function removeNote(Notes $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getUser() === $this) {
                $note->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Games[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Games $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->addUser($this);
        }

        return $this;
    }

    public function removeGame(Games $game): self
    {
        if ($this->games->removeElement($game)) {
            $game->removeUser($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->email;
    }
}

src/Form/GamesType.php
<?php

namespace App\Form;

use App\Entity\Games;
use App\Entity\Genres;
use App\Entity\Users;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GamesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
             
/*             ->add('title')
            ->add('Description')
            ->add('Image', FileType::class, [
                'label' => 'Image',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'image/*',
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid document',
                    ])
                ],
            ])
            ->add('genres', EntityType::class, [
                'class' => Genres::class,
                'choice_label' => 'Title',
                'multiple' => true,
                'expanded' => true
            ])  */
            ->add('users', EntityType::class, [
                'class' => Users::class,
                'choice_label' => 'email',
                'multiple' => true,
                'expanded' => true
            ]) 
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Games::class,
        ]);
    }
}

templates/games/fav.html.twig
{% extends 'base.html.twig' %} 

{% form_theme formFav 'bootstrap_5_layout.html.twig' %}


{% block body %}

{% if game.favorite == false %}
<p>Votre favori a bien été supprimé</p>
{% else %}
<p>Votre favori a bien été ajouté</p>
{% endif %}
<a class="nav-link" aria-current="page" href="{{ path('games') }}?fav">Retour favoris</a>
            
{% endblock %}

templates/games/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% if (app.request.requestUri == '/games?fav') %}
        Favoris
    {% else %}
        Jeux
    {% endif %}
{% endblock %}

{% block body %}

</div>

<section id="games">
    {% if (app.request.requestUri == '/games?fav') %}
    <h2>Favoris</h2>
    {% else %}
    <h2>Jeux</h2>
    {% endif %}
</section>

<div class="container py-3">
    <div class="row align-items-center">
        <div class="col-6">
            <form class="flex-row" id="filters" method="get" action="">
                <label class="mx-2" for="genres[]">Genres</label>
                    <select name="genres[]" id="genres[]" multiple>
                    {% for genre in genres %}
                        <option value="{{ genre.id }}">{{ genre.title }}</option>
                    {% endfor %}
                    </select>
                <button type="submit" class="btn btn-yellow mx-3 w-25">Filtrer</button>
            </form>
        </div>
        <div class="col-6">
            <form class="flex-row" id="order" method="get" action="">
                <label class="mx-2" for="order">Ordre</label>
                    <select name="order" id="order">
                        <option value="asc">A-Z</option>
                        <option value="desc">Z-A</option>
                    </select>
                <button type="submit" class="btn btn-yellow mx-3 w-25">Valider</button>
            </form>
        </div>
    </div>

    <div class="row results-list">
        {% for game in games %}
        <div class="col cards-container d-flex justify-content-evenly">
            <div class="card-one">
                <header>
                    <div class="image">
                        <img src="{{ asset('uploads/images_games/' ~ game.image) }}" alt="photo jeux" />
                    </div>
                </header>
                <div class="infos">
                    <h3><strong>{{ game.title }}</strong></h3>
                </div>
                <div class="desc">
                    <p>{{ game.description | raw }}</p>
                </div>
                <div class="promotion">
                    {% for genre in game.genres %}
                    <p class="promotion-bordure">{{ genre }}</p>
                    {% endfor %}
                </div>
                <div class="skills row">
                    <p> Crée le {{ game.date | date('d/m/Y') }} à {{ game.date | date('H:i')}}</p>
                </div>

                <footer>
                    <a href="{{ game.url }}" target="_blank"><i class="fas fa-gamepad mr-1"></i>Jouer</a>
                    <a href="{{ path('games_show', {'id' : game.id}) }}"><i class="fas fa-book-reader mr-1"></i>Avis</a>
                        {% if app.user.pseudonyme is defined %}
                            {% if game.favorite == true %}
                                <a href="{{ path('games_fav', {'id' : game.id}) }}" <i class="fas fa-heart coeur"></i></a>
                            {% else %}
                                <a href="{{ path('games_fav', {'id' : game.id}) }}" <i class="far fa-heart"></i></a>
                            {% endif %}
                        {% else %}
                        {% endif %}
                </footer>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</section>

{% endblock %}

templates/games/show.html.twig
{% extends 'base.html.twig' %} 

{% form_theme formNote 'bootstrap_5_layout.html.twig' %}

{% block title %}{{ game.title }}{% endblock %}

{% block body %}
</div>
<section id="show" class="d-flex flex-column py-5">
    <div class="row mt-3">
        <div class="title d-flex align-items-center mb-3">
            <h2 class="mr-5">{{ game.title }}</h2>
            {% if game.favorite == true %}
                <a href="{{ path('games_fav', {'id' : game.id}) }}" <i class="fas fa-heart coeur fa-3x m-left"></i></a>
            {% else %}
            <a href="{{ path('games_fav', {'id' : game.id}) }}" <i class="far fa-heart fa-3x m-left"></i></a>
            {% endif %}
        </div>  
    </div>

    <div class="row text-center">  
        <div class="note mb-4">
            {% if avg.content|number_format(1) != 0 %}
                <div class="Stars" style="--rating: {{ avg.content|number_format(1) }}">{{ avg.content|number_format(1) }}/5</div>
            {% else %}
                <div class="Stars" style="--rating: {{ avg.content|number_format(1) }}">Non noté</div>
            {% endif %}
        </div>      
        <div class="metadata">
            <em><p class="mb-3">Crée le {{ game.date | date('d/m/Y') }} à {{ game.date | date('H:i')}}</p></em>
        </div>
        {% if game.genres|length == 0 %}
            <div class="genres mb-4">
                Aucun genre défini.
            </div>
        {% endif %}

        {% if game.genres|length == 1 %}
            {% for genre in game.genres %}
                <div class="genres mb-3">
                    <strong><u>Genre :</u></strong> {{genre}}
                </div>
            {% endfor %}
        {% endif %}

        {% if game.genres|length > 1 %}
            <div class="genres mb-3">
                <strong><u>Genres :</u></strong>
                {% for genre in game.genres %}
                    {{genre}}
                {% endfor %}
            </div>
        {% endif %}
        </div> 
    </div>

    <div class="row align-items-center">
        <div class="col-6 d-flex justify-content-center">
            <img src="{{ asset('uploads/images_games/' ~ game.image) }}" alt="image jeu" width="300px">
        </div>
        <div class="col-6 d-flex justify-content-center">
            <p>{{ game.description | raw }}</p>
        </div>
    </div>
</section>
  
<div class="container coms my-5">
    <div class="row d-flex">
        <div class="col-md-8">
            <div class="headings d-flex justify-content-between align-items-center mb-3">
                <h2 class="mb-3">Commentaires<h2>
            </div>
            {% for note in game.notes %}
                {% if note.etat == 1 %}
                    <div class="card py-3 my-3">
                        <div class="d-flex justify-content-between align-items-center mx-3">
                            <div class="user d-flex flex-row align-items-center"> 
                                <span>
                                    <strong><small class="font-weight-bold pseudo mr-2">{{ note.user.pseudonyme }}</small></strong>
                                    <small class="font-weight-bold">{{ note.description }} </small>
                                </span> 
                            </div> 
                            <small>{{ note.date | date('d/m/Y') }} à {{ note.date | date('H:i')}}</small>
                        </div>
                        <div class="Stars_min mx-3" style="--rating: {{ note.note }}"></div>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<section id="comment">
    <div class="container d-flex flex-column align-items-center justify-content-center">
        {% if app.user.pseudonyme is defined %}
        <h2 class="mb-5">Ajouter un commentaire</h2>
            {{ form_start(formNote) }}
            <div class="reg-form">

            {{ form_label(formNote.description) }}
            {{ form_widget(formNote.description, {'attr': {'class': 'mt-1 mb-4'}}) }}

            {{ form_label(formNote.note) }}
            {{ form_widget(formNote.note, {'attr': {'class': 'mt-1 mb-4'}}) }}    
            <button type="submit" class="btn btn-yellow mt-3">Envoyer</button>
            </div>
            {{ form_end(formNote) }}
        {% else %}
        <label>Veuillez vous <u><a href="{{ path('app_login') }}">connecter</a></u> pour ajouter un avis.</label>
        {% endif %}
    </div>
</div>
{% endblock %}